services:
  service1:
    executable: "service1.py"
  vibration:
    executable: "service_vibration.py"
  voltage:
    executable: "service_voltage.py"
  pms:
    executable: "service_pms.py"
  tempHumi:
    executable: "service_tempHumi.py"  

mqtt_config:
  BROKER_ADDRESS: "172.27.51.73"
  PORT: 1883
  REQUEST_TOPIC: "request/+/service"
  USERNAME: "eason"
  PASSWORD: "qazwsx"
