services:
  service1:
    executable: "service1.py"
  service2:
    executable: "service2.py"
  service3:
    executable: "service3.py"

mqtt_config:
  BROKER_ADDRESS: "172.27.51.73"
  PORT: 1883
  REQUEST_TOPIC: "request/+/service"
  USERNAME: "eason"
  PASSWORD: "qazwsx"
