services:
  service1:
    executable: "service1.py"
  service_vibration:
    executable: "service_vibration.py"
  service_voltage:
    executable: "service_voltage.py"
  service_pms:
    executable: "service_pms.py"
  service_temphumi:
    executable: "service_temphumi.py"  

mqtt_config:
  BROKER_ADDRESS: "172.27.51.73"
  PORT: 1883
  REQUEST_TOPIC: "request/+/service"
  USERNAME: "eason"
  PASSWORD: "qazwsx"
